#!/bin/bash


tags=""

#https://stackoverflow.com/questions/369758/how-to-trim-whitespace-from-a-bash-variable
trim() {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"   
    echo -n "$var"
}


#https://stackoverflow.com/questions/19408649/pipe-input-into-a-script
if [ -p /dev/stdin ]; then
    while IFS= read tag; do
        tags="$tags $(trim $tag)"
    done

fi

for tag in "$@"; do
    tags="$tags $(trim $tag)"
done


if [ -z "$tags" ]; then
    echo >&2 ""
    echo >&2 "silentfrompdbs by bcov - a tool to make a silent file from pdbs"
    echo >&2 "Usage:"
    echo >&2 "        cat list_of_tags.list | silentfrompdbs > silent.silent"
    echo >&2 "                             or"
    echo >&2 "        silentfrompdbs tag1 tag2 tag3 > silent.silent"
    exit 1
fi



tmp_file=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13)
tmp_file="tmp_${tmp_file}.silent"

score_jd2 -s $tags -out:file:silent $tmp_file -out:file:silent_struct_type binary 1>&2

silentls $tmp_file | sed 's/_0001$//g' | silentrename $tmp_file

rm $tmp_file
rm $tmp_file.idx



