#!/usr/bin/env python

import os
import sys
# if you pip installed this is wrong but you have silent_tools installed anyways
silent_tools_dir = os.path.dirname(os.path.realpath(__file__))
if silent_tools_dir not in sys.path:
    sys.path.append(silent_tools_dir)

import silent_tools
from silent_tools import eprint
import re
import stat

# Don't throw an error when someone uses head
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE, SIG_DFL) 

all_args = sys.argv[1:]
b_flag = False
for i in range(len(all_args)-1, -1, -1):
    elem = all_args[i]
    if elem[0] != '-':
        continue
    if elem[1] == 'b':
        b_flag = True
        all_args.pop(i)
        break
    assert False, 'silentrename: Unknown flag ' + elem


if (len(all_args) == 0):
    eprint("")
    eprint('silentrename by bcov - a tool to rename the tags of a silent file')
    eprint("Usage:")
    eprint("        cat list_of_tags.list | silentrename myfile.silent > new.silent")
    eprint("                             or")
    eprint("        silentrename myfile.silent tag1 tag2 tag3 > new.silent")
    eprint("")
    eprint("Important! You must pass the same number of tags that there are in the")
    eprint("    silent file.")
    eprint("")
    eprint("Flags:")
    eprint("        -b Broadcast mode: A silent file with 1 structure can be duplicated with arbitrarily many names")
    eprint("")
    eprint("Example usage:")
    eprint("")
    eprint("silentls my.silent > tags.list")
    eprint("vi tags.list")
    eprint("cat tags.list | silentrename my.silent > new.silent")
    eprint("")
    eprint("silentls my.silent | sed 's/_0001$//g' | silentrename my.silent > new.silent")
    sys.exit(1)

silent_file = all_args[0]

tag_buffers = []
if ( stat.S_ISFIFO(os.stat("/dev/stdin").st_mode) ):
    tag_buffers += sys.stdin.readlines()
tag_buffers += all_args[1:]

any_spaces = False
tags = []
for line in tag_buffers:
    line = line.strip()
    if (len(line) == 0):
        continue
    tags.append(line)
    if ' ' in line:
        any_spaces = True

if any_spaces:
    eprint("Warning!!! There are spaces in the names of your designs!"
        " Unless you really know what you're doing this is going to break the silent file")


silent_index = silent_tools.get_silent_index( silent_file )

if b_flag:
    if len(silent_index['tags']) != 1:
        eprint("Error! -b implies that the silent file should have exactly 1 structure")
else:
    if (len(silent_index['tags']) != len(tags)):
        eprint("Error! Number of input tags (%i) is not equal to number of tags in silent file (%i)!"%
            (len(tags), len(silent_index['tags'] )))
        sys.exit(1)


sys.stdout.write( silent_tools.silent_header( silent_index ) )
sys.stdout.flush()

# old slow
# with open(silent_file) as sf:
#     for itag in range(len(tags)):

#         index_tag = silent_index['tags'][itag]
#         structure = silent_tools.get_silent_structure_file_open( sf, silent_index, index_tag )

#         original_tag = silent_index['orig_tags'][itag]
#         sys.stdout.write("".join(structure).replace(original_tag, tags[itag]))
#         sys.stdout.flush()


total_structures = len(tags)
seek_size = 1 if b_flag else 1000
cur_struct = 0
cur_write = 0

with open(silent_file, errors='ignore') as sf:
    while cur_struct < total_structures:

        if ( cur_struct + seek_size > total_structures ):
            seek_size = total_structures - cur_struct

        if not b_flag or cur_struct == 0:
            structures = silent_tools.get_silent_structures_true_slice( sf,
                                silent_index, cur_struct, cur_struct+seek_size, True )

        for structure in structures:
            original_tag = silent_index['orig_tags'][0 if b_flag else cur_write]
            sys.stdout.write(structure.replace(original_tag, tags[cur_write]))
            sys.stdout.flush()
            cur_write += 1

        cur_struct += seek_size

        assert(cur_write == cur_struct)



