#!/usr/bin/env python

import os
import sys
# if you pip installed this is wrong but you have silent_tools installed anyways
silent_tools_dir = os.path.dirname(os.path.realpath(__file__))
if silent_tools_dir not in sys.path:
    sys.path.append(silent_tools_dir)

import silent_tools
from silent_tools import eprint
import stat
import math
import shutil
import io
import numpy as np

os.environ['CCD_MIRROR_PATH'] = ''
os.environ['PDB_MIRROR_PATH'] = ''
import atomworks 
# Don't throw an error when someone uses head
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE, SIG_DFL) 



cif_buffers = []
if ( stat.S_ISFIFO(os.stat("/dev/stdin").st_mode) ):
    cif_buffers += sys.stdin.readlines()
cif_buffers += sys.argv[1:]

if (len(cif_buffers) == 0):
    eprint("")
    eprint('silentsketchfromcifs by bcov - generates a silent from from cifs WITHOUT rosetta')
    eprint("Usage:")
    eprint("        cat list_of_cifs.list | silentsketchfromcifs > new.silent")
    eprint("                             or")
    eprint("        silentsketchfromcifs 1.cif 2.cif 3.cif > new.silent")
    eprint("Flags:")
    eprint("        -j cpus")
    sys.exit(1)


cifs = []
for line in cif_buffers:
    line = line.strip()
    if (len(line) == 0):
        continue
    sp = line.split(" ")
    for cif in sp:
        cifs.append(cif)

j_flag = None
for i in range(len(cifs)-1, -1, -1):
    elem = cifs[i]
    if elem[0] != '-':
        continue
    if elem[1] == 'j':
        if len(elem) == 2:
            if i == len(cifs) - 1:
                assert False, 'silentsketchfromcifs: Error, no argument for -j'
            else:
                j_flag = int(cifs[i+1])
                cifs.pop(i+1)
                cifs.pop(i)
        else:
            j_flag = int(elem[2:])
            cifs.pop(i)
        break
    assert False, 'silentsketchfromcifs: Unknown flag ' + elem



if j_flag is not None:
    this_file = os.path.realpath(__file__)
    tmp_dir = 'tmp_' + silent_tools.random_string(13)
    os.mkdir(tmp_dir)
    per_file = int(math.ceil( len(cifs) / j_flag ))
    for i in range(j_flag):
        file = os.path.join(tmp_dir, 'tmp_%i.list'%i)
        with open(file, 'w') as f:
            f.write('\n'.join(cifs[i*per_file:(i+1)*per_file]))
            f.write('\n')
    stdout, stderr, code = silent_tools.cmd2(f'ls {tmp_dir}/tmp* | parallel -j{j_flag} "cat {{}} | {this_file}"')
    try:
        shutil.rmtree(tmp_dir)
    except:
        pass
    if len(stdout.strip()) > 0:
        print(stdout.strip())
    if len(stderr.strip()) > 0:
        eprint(stderr.strip())
    sys.exit(code)




pre_tags = [os.path.basename(cifs) for cifs in cifs]

if (len(cifs) != len(set(cifs))):
    eprint("silentfastslice: Warning: %i duplicate paths specified"%(len(cifs) - len(set(cifs))))

if (len(pre_tags) != len(set(pre_tags))):
    eprint("silentfastslice: Warning: %i paths have duplicate names/tags. Going to rename duplicates to _1"%(len(pre_tags) - len(set(pre_tags))))



dup_index = {}
all_tags = set()

first = True
for cif in cifs:
    tag = os.path.basename(cif)
    if tag.endswith('.gz'):
        tag = tag[:-len('.gz')]
    if tag.endswith(".cif"):
        tag = tag[:-len('.cif')]

    # Deal with duplicate names
    if tag in all_tags:
        if tag in dup_index:
            number = dup_index[tag]
        else:
            number = 1

        while tag + "_%i"%number in all_tags:
            number += 1

        dup_index[tag] = number

        tag = tag + "_%i"%number

    all_tags.add(tag)

    if not os.path.exists(cif):
        eprint("silentsketchfromcifs: Error! cif does not exist:", cif)
        continue

    # try:
    #     cif_lines = open(cif).readlines()
    # except:
    #     eprint("silentsketchfromcifs: Error! cif couldn't be opened", cif)
    #     continue


    structure = atomworks.io.parser.parse(cif)['asym_unit'][0]
    structure_with_h = atomworks.io.parser.parse_atom_array(structure, hydrogen_policy='infer')['asym_unit'][0]

    # atomworks really drops the ball on inferring hydrogens on ligands
    hetero_h_mask = (structure.element == 'H') & structure.hetero
    hetero_h = structure[hetero_h_mask]
    hetero_h_set = set([tuple(x) for x in zip(hetero_h.chain_id, hetero_h.res_id, hetero_h.res_name, hetero_h.atom_name)])

    new_hetero_h_mask = (structure_with_h.element == 'H') & structure_with_h.hetero
    new_hetero_h = structure_with_h[new_hetero_h_mask]
    is_old = np.array([tuple(x) in hetero_h_set for x in zip(new_hetero_h.chain_id, new_hetero_h.res_id, new_hetero_h.res_name, new_hetero_h.atom_name)])
    keep_mask = ~new_hetero_h_mask
    keep_mask[np.where(new_hetero_h_mask)[0][is_old]] = True
    structure_with_h = structure_with_h[keep_mask]


    structure_with_h = atomworks.io.parser.parse_atom_array(structure_with_h)['asym_unit'][0]


    if int(structure_with_h.res_name.dtype.str.replace('<U', '')) > 3:
        structure_with_h.res_name = structure_with_h.res_name.astype('<U3')
    pdb_lines = atomworks.io.utils.io_utils.to_pdb_string(structure_with_h[~np.isnan(structure_with_h.coord).any(axis=-1)]).split('\n')
    # with open('tmp.pdb', 'w') as f:
    #     f.write('\n'.join(pdb_lines))


    sys.stdout.write(''.join(silent_tools.pdb_to_structure(pdb_lines, tag, write_header=first, allow_extra_atoms=True )))
    sys.stdout.flush()
    first = False



