#!/usr/bin/env python

import distutils.spawn
import os
import sys
sys.path.append(os.path.dirname(distutils.spawn.find_executable("silent_tools.py")))
import silent_tools
from silent_tools import eprint

# Don't throw an error when someone uses head
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE, SIG_DFL) 

if (len(sys.argv) == 1):
    eprint("")
    eprint('silentslice by bcov - a tool to allow you extract a smaller silent file from a larger one')
    eprint("Usage:")
    eprint("        cat list_of_tags.list | silentslice myfile.silent > new.silent")
    eprint("                             or")
    eprint("        silentslice myfile.silent tag1 tag2 tag3 > new.silent")
    sys.exit(1)

silent_file = sys.argv[1]

tags = []
for line in sys.stdin.readlines() + sys.argv[2:]:
    line = line.strip()
    if (len(line) == 0):
        continue
    tags.append(line)


silent_index = silent_tools.get_silent_index( silent_file )

structures = silent_tools.get_silent_structures( silent_file, silent_index, tags )

to_print = silent_tools.silent_header( silent_index )

for structure in structures:
    to_print += "".join(structure)

print(to_print)