#!/usr/bin/env python

import distutils.spawn
import os
import sys
sys.path.append(os.path.dirname(distutils.spawn.find_executable("silent_tools.py")))
import silent_tools


files = sys.argv[1:]


for ifile in range(len(files)):

    file = files[ifile]

    if (len(files) > 1):
        print(file + ":")

    with open(file) as f:
        silent_offsets, silent_tags, scoreline = silent_tools.silent_parse( f )

    for tag in silent_tags:
        print(tag)

    if (ifile + 1 < len(files)):
        print("")

