#!/usr/bin/env python

import os
import sys
# if you pip installed this is wrong but you have silent_tools installed anyways
silent_tools_dir = os.path.dirname(os.path.realpath(__file__))
if silent_tools_dir not in sys.path:
    sys.path.append(silent_tools_dir)

import silent_tools
from silent_tools import eprint

# Don't throw an error when someone uses head
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE, SIG_DFL)


if len(sys.argv) != 2:
    eprint("")
    eprint("silentscorefile by bcov - a tool to extract a scorefile from a silentfile")
    eprint("Usage:")
    eprint("        silentscorefile myfile.silent")
    eprint("")
    eprint("Note: This utility ensures that all score lines contain the same elements in")
    eprint("       the same order. If this is not the case, multiple scorefiles are produced")
    sys.exit(1)

silent_file = sys.argv[1]

if not os.path.isfile(silent_file):
    eprint("silentscorefile: File not found: %s" % silent_file)
    sys.exit(1)

scores = silent_tools.extract_score_files(silent_file)

# Check for duplicate tags (last column of each row is the description/tag)
all_tags = []
for rows in scores.values():
    for row in rows:
        all_tags.append(row[-1])

seen = set()
duplicates = set()
for tag in all_tags:
    if tag in seen:
        duplicates.add(tag)
    seen.add(tag)

if duplicates:
    eprint('')
    eprint('==== WARNING!!! Tags in silent file are not unique! ====')
    eprint('')
    eprint('  Fix with: silentls %s | silentrename %s > fixed.silent' % (silent_file, silent_file))

silentname = os.path.splitext(os.path.basename(silent_file))[0]

num_types = len(scores)

if num_types == 1:
    header, rows = next(iter(scores.items()))
    scorename = silentname + '.sc'
    with open(scorename, 'w') as f:
        f.write(' '.join(header) + '\n')
        for row in rows:
            f.write(' '.join(row) + '\n')
else:
    # Don't change this wording unless you change silentinjectscores
    eprint("Warning!! Multiple scorefiles produced!!")
    for i, header in enumerate(scores.keys(), 1):
        eprint(' '.join(header))
        scorename = silentname + str(i) + '.sc'
        rows = scores[header]
        with open(scorename, 'w') as f:
            f.write(' '.join(header) + '\n')
            for row in rows:
                f.write(' '.join(row) + '\n')
